### ISSUE TITLE
hi, will it also have livelinkpose?

### ISSUE THREAD

**Issue by lucasjinreal** [think-biq/LLV#3]
this is useful, now that we have livelink face, will it have livelink pose streaming from pose sending pose data into ue as well?
I am really hope for it.

**Comment by BlurryRoots** [comment]
Ahoj @jinfagang, glad you found value in LLV. Would you be so kind as to specify what you mean by pose streaming? Where would the data be coming from?

**Comment by lucasjinreal** [comment]
@BlurryRoots let's continue the original question here. (be 100% relax I have no willing to redistribute your work or do anything bad, I just for learn and using in my in-house project which not probably open source but I would like contribute to your main repo if you like).


I am currently really want sending body pose data to metahman in a same way as AppleARKit face through livelink, but I have no idea what's it need (the data format, the k and values it need). I presume you create the repo might have same ultimate goal to sending both face and body pose data to remote control metahumans.

**Comment by BlurryRoots** [comment]
The reason for developing of LLV was originally for debugging purposes. Yet it seems some people use it for various purposes in their animation production pipeline. I checked out your commits and it appears as if you are trying to use baked animations from OBJ files. I pressume those are blender exported OBJs, since the original file format does not specify support for animations per se. Anyhow, so am I getting this right, that you would like to stream those animation frames read from the OBJ as pose frames for the control rig of a MetaHuman character in UE through LiveLink?

**Comment by lucasjinreal** [comment]
@BlurryRoots Partially right, am not using obj, 😭, honestly, I currently just renamed packaged name and fixed install, some commits didn't pushed yet which is added PoseFrame.

My ultimate goal is streaming data from my neuralnetwork model to UE5 (be note that this is different than loading local files but essentially same).

So one more step I need to do is add Pose data as well, do u have any knowledge about this?  (Also, the pose is not frame obj, it's frome my NN model as well, but I need to take a DAE or FBX animation as test first)

**Comment by BlurryRoots** [comment]
No plans to add pose frames yet. But would welcome any suggestions or pull request.

**Comment by BlurryRoots** [comment]
No plans to add pose frames yet. But would welcome any suggestions or pull request.
